SELECT *
FROM
  (
  SELECT
    LINK_NO, URI, UPI_NUMBER, CIS_MARKER, ADMISSION_TYPE,
    ADMISSION_DATE, DISCHARGE_DATE,
    MAIN_CONDITION ||','|| OTHER_CONDITION_1 ||','||
    OTHER_CONDITION_2 ||','|| OTHER_CONDITION_3 ||','|| 
    OTHER_CONDITION_4 ||','|| OTHER_CONDITION_5 AS CONDITIONS,
    AGE_IN_YEARS, SEX, LENGTH_OF_STAY, COUNCIL_AREA_2019, DATAZONE_2011
  FROM
    ANALYSIS.SMR01_PI
  WHERE
    (ADMISSION_DATE >= TO_DATE('2015-04-01','yyyy/mm/dd')) AND
    (ADMISSION_DATE <= TO_DATE('2020-03-31','yyyy/mm/dd')) 
    
  )
WHERE
  REGEXP_LIKE (CONDITIONS, '%W[00-19]%')
/*SELECT *
FROM #RESULT_1
WHERE REGEXP_LIKE (CONDITIONS, '%W[00-19]%')
ORDER BY
  LINK_NO, CIS_MARKER, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_TYPE DESC*/