SELECT * /*
  LINK_NO, URI, UPI_NUMBER, CIS_MARKER, ADMISSION_TYPE,
  ADMISSION_DATE, DISCHARGE_DATE,
  MAIN_CONDITION, OTHER_CONDITION_1, OTHER_CONDITION_2,
  OTHER_CONDITION_3, OTHER_CONDITION_4, OTHER_CONDITION_5,
  AGE_IN_YEARS, SEX, LENGTH_OF_STAY, datazone_2011 /*, COUNCIL_AREA*/
FROM
  ANALYSIS.SMR01_PI
WHERE
  (DISCHARGE_DATE >= TO_DATE('%s','yyyy/mm/dd')) AND
  (DISCHARGE_DATE <= TO_DATE('%s','yyyy/mm/dd')) AND
  ROWNUM<=10
  
ORDER BY
  LINK_NO, CIS_MARKER, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_TYPE DESC