SELECT
  LINK_NO, URI, UPI_NUMBER, CIS_MARKER, ADMISSION_TYPE,
  ADMISSION_DATE, DISCHARGE_DATE,
  MAIN_CONDITION, OTHER_CONDITION_1, OTHER_CONDITION_2,
  OTHER_CONDITION_3, OTHER_CONDITION_4, OTHER_CONDITION_5,
  AGE_IN_YEARS, SEX, LENGTH_OF_STAY, COUNCIL_AREA_2019, DATAZONE_2011,
  hbres_keydate, hbres_currentdate
FROM
  ANALYSIS.SMR01_PI
WHERE
  (DISCHARGE_DATE >= TO_DATE('%s','yyyy/mm/dd')) AND
  (DISCHARGE_DATE <= TO_DATE('%s','yyyy/mm/dd')) AND
  (ADMISSION_TYPE IN (33,34,35)) /*AND
  (
    REGEXP_LIKE(main_condition,'^W[00-19]') OR
    REGEXP_LIKE(other_condition_1,'^W[00-19]') OR
    REGEXP_LIKE(other_condition_2,'^W[00-19]') OR
    REGEXP_LIKE(other_condition_3,'^W[00-19]') OR
    REGEXP_LIKE(other_condition_4,'^W[00-19]') OR
    REGEXP_LIKE(other_condition_5,'^W[00-19]')
   ) AND
   ROWNUM<=10000 */
   
ORDER BY
  LINK_NO, CIS_MARKER, ADMISSION_DATE, DISCHARGE_DATE, ADMISSION_TYPE DESC